organization: Andrew Stucki
top_level_license: "MIT"
matches:
  - type: go
    short: true
    extension: .go
    directory: templater
    license: MIT
  - delimiter: # defines a custom delimiter pattern to use
      top: "{{- /*"
      bottom: "*/ -}}"
    short: true
    extension: .tpl
    directory: templater
    license: MIT