version: '3'

# if a task is referenced multiple times, only run it once
run: once

# configure bash to recursively expand **
shopt: [globstar]

tasks:
  pending-prs:
    desc: "Get all pending PRs for watched branches"
    silent: true
    cmds:
      - ./.github/workflows/scripts/pending-prs terminal andrewstucki/actions-testing
