name: Auto-Approve Backport

on:
  pull_request:

jobs:
  approve:
    name: Auto-approve backport
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'backport/') && (github.actor == 'robo-turtle')
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4